services:
  db:
    image: db
    build: 
      context: .
      target: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=event-management-system
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      # - ./data.sql:/tmp/seed.sql