CREATE SCHEMA IF NOT EXISTS ems_sponsor;
CREATE SCHEMA IF NOT EXISTS ems_attendee;
CREATE SCHEMA IF NOT EXISTS ems_organizer;
CREATE SCHEMA IF NOT EXISTS ems_event;
CREATE SCHEMA IF NOT EXISTS ems_ticket;