CREATE SCHEMA IF NOT EXISTS ems_ticket;

CREATE TYPE TICKET_TYPE_ENUM AS ENUM ('GENERAL_ADMISSION', 'VIP', 'STUDENT', 'WORK');

CREATE TABLE IF NOT EXISTS ems_ticket.tickets (
  id UUID PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  last_updated TIMESTAMP WITH TIME ZONE NOT NULL,
  event_id UUID NOT NULL,
  ticket_type TICKET_TYPE_ENUM NOT NULL,
  price INTEGER NOT NULL,
  transferable BOOLEAN NOT NULL,
  seat TEXT NOT NULL,
  section TEXT NOT NULL
);

ALTER TABLE ems_ticket.tickets
    ADD COLUMN used BOOLEAN NOT NULL DEFAULT FALSE;