name: SonarCloud Scan

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - 'master'

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.2.0
      with:
         args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION_KEY }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=event-management-system/src/main/java/
            -Dsonar.tests=event-management-system/src/test/java/
            -Dsonar.java.binaries=.
            -Dsonar.language=java
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}